# Deployment for running a CCDScan Backend instance, including a TimescaleDB instance.
# The backend may be run as an existing (official) image or built from local source.
# See the readme for usage.

version: "3"
services:
  backend:
    image: ${CCDSCAN_BACKEND_IMAGE-concordium/ccdscan:test}
    build: ./backend
    ports:
    - "${CCDSCAN_BACKEND_PORT-5000}:5000"
    environment:
    - ImportValidation__Enabled=false
    - ConcordiumNodeGrpc__AuthenticationToken=rpcadmin
    - ConcordiumNodeGrpc__Address=${CCDSCAN_NODE_GRPC_ADDRESS-http://172.17.0.1:10000}
    - PostgresDatabase__ConnectionString=Host=timescaledb;Port=5432;Database=ccscan;User ID=postgres;Password=password;Include Error Detail=true;
    - PostgresDatabase__ConnectionStringNodeCache=Host=timescaledb;Port=5432;Database=ccscan_node_cache;User ID=postgres;Password=password;Include Error Detail=true;
    - FeatureFlags__ConcordiumNodeImportEnabled=true
    - FeatureFlags__MigrateDatabasesAtStartup=true
    - NodeCollectorService__Address=https://dashboard.${CCDSCAN_DOMAIN-testnet.concordium.com}/nodesSummary
    networks:
    - ccdscan
    depends_on:
    - timescaledb
    restart: unless-stopped  # it seems like startup sometimes fails because the DB isn't ready yet
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - ./debug/timescaledb:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  node:
    image: concordium/testnet-node:5.1.3-0
    ports:
      - ${CONCORDIUM_NODE_PORT}:${CONCORDIUM_NODE_PORT}
      - ${CONCORDIUM_NODE_GRPC2_LISTEN_PORT}:${CONCORDIUM_NODE_GRPC2_LISTEN_PORT}
    working_dir: /
    environment:
      ## Refer https://github.com/Concordium/concordium-node/blob/main/VARIABLES.md#grpc
      CONCORDIUM_NODE_GRPC2_LISTEN_ADDRESS: 0.0.0.0
      CONCORDIUM_NODE_GRPC2_LISTEN_PORT: ${CONCORDIUM_NODE_GRPC2_LISTEN_PORT}
      CONCORDIUM_NODE_RPC_SERVER_ADDR: 0.0.0.0
      CONCORDIUM_NODE_RPC_SERVER_PORT: ${CONCORDIUM_NODE_PORT}
      CONCORDIUM_NODE_LISTEN_ADDRESS: 0.0.0.0
      CONCORDIUM_NODE_CONSENSUS_GENESIS_DATA_FILE: /testnet-genesis.dat
      CONCORDIUM_NODE_CONFIG_DIR: "/node/concordium-node-data"
      CONCORDIUM_NODE_DATA_DIR: "/node/concordium-node-config"
      CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES: bootstrap.testnet.concordium.com:8888
    volumes:
      - ./dist/node/data:/node/concordium-node-data
      - ./dist/node/config:/node/concordium-node-config
    entrypoint:
      - ./concordium-node
volumes:
  ccdscan:
networks:
  ccdscan:
